from django.conf.urls import url
from . import views 
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# This code is for creating new pages and redirecting to their URLS.
from django.contrib.auth import views as auth_view # this is for pw-reset

urlpatterns = [

    # Login or Index
    url(r'^$', views.index, name='index'),
    url(r'^AboutUs/$', views.aboutUs, name='aboutUs'),

    
    # Chairperson
    url(r'^chairperson/$', views.chairperson, name='chairperson'),
    url(r'^choose_one/$', views.choose_one, name='choose_one'),
    url(r'^chairperson_profile/$', views.chairperson_profile, name='chairperson_profile'),
    url(r'^chairperson_edit_profile/$', views.chairperson_edit_profile, name='chairperson_edit_profile'),
    url(r'^chairperson_change_password/$', views.chairperson_change_password, name='chairperson_change_password'),
    url(r'^cfaculty_applicant/$', views.cfaculty_applicant, name='cfaculty_applicant'),
    path(r'^cfaculty_applicant-Master/', views.cfacultyapplicant_sortedlist, name='cfaculty_applicant-Master'),
    path('faculty_view/<faculty_id>', views.faculty_view, name='faculty_view'),
    path('emailApplicant/<faculty_id>', views.emailApplicant, name='emailApplicant'),
    path(r'emailTrans/<trans_id>', views.emailTrans, name='emailTrans'),
    path(r'emailShifter/<shifter_id>', views.emailShifter, name='emailShifter'),
    path('sendmailfile/<faculty_id>', views.sendmailfile, name='sendmailfile'),

    url(r'^Department/$', views.is_active, name='is_active'),
    path('is_subject_view/<dept_id>', views.is_subject_view, name='is_subject_view'),
    url(r'^sc_active/$', views.sc_active, name='sc_active'),
    path('sc_subject_view/<dept_id>', views.sc_subject_view, name='sc_subject_view'),

    path('StudentProfile/<dept_id>', views.profile1_1, name='profile1_1'),
    url(r'^dept_student/$', views.dept_student, name='dept_student'),

    url(r'^All_Students/$', views.students_all, name='students_all'),
    url(r'^All_Students_Irregular/$', views.students_allI, name='students_allI'),
    url(r'^BSIT_1st_Year/$', views.students_bsit, name='students_bsit'),
    url(r'^BSIT_1st_Year_I/$', views.students_bsit1I, name='students_bsit1I'),
    url(r'^BSIT_2nd_Year/$', views.students_bsit2, name='students_bsit2'),
    url(r'^BSIT_2nd_Year_I/$', views.students_bsit2I, name='students_bsit2I'),
    url(r'^BSIT_3rd_Year/$', views.students_bsit3, name='students_bsit3'),
    url(r'^BSIT_3rd_Year_I/$', views.students_bsit3I, name='students_bsit3I'),
    url(r'^BSIT_4th_Year/$', views.students_bsit4, name='students_bsit4'),
    url(r'^BSIT_4th_Year_I/$', views.students_bsit4I, name='students_bsit4I'),
    url(r'^BSIT_5th_Year/$', views.students_bsit5, name='students_bsit5'),
    url(r'^BSIT_5th_Year_I/$', views.students_bsit5I, name='students_bsit5I'),
    url(r'^BSIT_6th_Year/$', views.students_bsit6, name='students_bsit6'),
    url(r'^BSIT_6th_Year_I/$', views.students_bsit6I, name='students_bsit6I'),

    url(r'^Students/$', views.students_bsit1, name='students_bsit1'),
    url(r'^BSIT_1st_Year_Block_2/$', views.students_bsit1_2, name='students_bsit1-2'),
    url(r'^BSIT_1st_Year_Block_3/$', views.students_bsit1_3, name='students_bsit1-3'),
    url(r'^BSIT_1st_Year_Block_4/$', views.students_bsit1_4, name='students_bsit1-4'),
    url(r'^BSIT_1st_Year_Block_5/$', views.students_bsit1_5, name='students_bsit1-5'),
    url(r'^BSIT_1st_Year_Block_6/$', views.students_bsit1_6, name='students_bsit1-6'),
    url(r'^BSIT_2nd_Year_Block_1/$', views.students_bsit2_1, name='students_bsit2-1'),
    url(r'^BSIT_2nd_Year_Block_2/$', views.students_bsit2_2, name='students_bsit2-2'),
    url(r'^BSIT_2nd_Year_Block_3/$', views.students_bsit2_3, name='students_bsit2-3'),
    url(r'^BSIT_2nd_Year_Block_4/$', views.students_bsit2_4, name='students_bsit2-4'),
    url(r'^BSIT_2nd_Year_Block_5/$', views.students_bsit2_5, name='students_bsit2-5'),
    url(r'^BSIT_2nd_Year_Block_6/$', views.students_bsit2_6, name='students_bsit2-6'),
    url(r'^BSIT_3rd_Year_Block_1/$', views.students_bsit3_1, name='students_bsit3-1'),
    url(r'^BSIT_3rd_Year_Block_2/$', views.students_bsit3_2, name='students_bsit3-2'),
    url(r'^BSIT_3rd_Year_Block_3/$', views.students_bsit3_3, name='students_bsit3-3'),
    url(r'^BSIT_3rd_Year_Block_4/$', views.students_bsit3_4, name='students_bsit3-4'),
    url(r'^BSIT_3rd_Year_Block_5/$', views.students_bsit3_5, name='students_bsit3-5'),
    url(r'^BSIT_3rd_Year_Block_6/$', views.students_bsit3_6, name='students_bsit3-6'),
    url(r'^BSIT_4th_Year_Block_1/$', views.students_bsit4_1, name='students_bsit4-1'),
    url(r'^BSIT_4th_Year_Block_2/$', views.students_bsit4_2, name='students_bsit4-2'),
    url(r'^BSIT_4th_Year_Block_3/$', views.students_bsit4_3, name='students_bsit4-3'),
    url(r'^BSIT_4th_Year_Block_4/$', views.students_bsit4_4, name='students_bsit4-4'),
    url(r'^BSIT_4th_Year_Block_5/$', views.students_bsit4_5, name='students_bsit4-5'),
    url(r'^BSIT_4th_Year_Block_6/$', views.students_bsit4_6, name='students_bsit4-6'),
    url(r'^BSIT_5th_Year_Block_1/$', views.students_bsit5_1, name='students_bsit5-1'),
    url(r'^BSIT_5th_Year_Block_2/$', views.students_bsit5_2, name='students_bsit5-2'),
    url(r'^BSIT_5th_Year_Block_3/$', views.students_bsit5_3, name='students_bsit5-3'),
    url(r'^BSIT_5th_Year_Block_4/$', views.students_bsit5_4, name='students_bsit5-4'),
    url(r'^BSIT_5th_Year_Block_5/$', views.students_bsit5_5, name='students_bsit5-5'),
    url(r'^BSIT_5th_Year_Block_6/$', views.students_bsit5_6, name='students_bsit5-6'),
    url(r'^BSIT_6th_Year_Block_1/$', views.students_bsit6_1, name='students_bsit6-1'),
    url(r'^BSIT_6th_Year_Block_2/$', views.students_bsit6_2, name='students_bsit6-2'),
    url(r'^BSIT_6th_Year_Block_3/$', views.students_bsit6_3, name='students_bsit6-3'),
    url(r'^BSIT_6th_Year_Block_4/$', views.students_bsit6_4, name='students_bsit6-4'),
    url(r'^BSIT_6th_Year_Block_5/$', views.students_bsit6_5, name='students_bsit6-5'),
    url(r'^BSIT_6th_Year_Block_6/$', views.students_bsit6_6, name='students_bsit6-6'),

    path('StudentProfileBSEE/<bsee_id>', views.profile1_1bsee, name='profile1_1bsee'),
    url(r'^BSEE_All/$', views.students_allbsee, name='students_allbsee'),
    url(r'^BSEE_AllI/$', views.students_allIbsee, name='students_allIbsee'),
    url(r'^BSEE/$', views.students_bsee, name='students_bsee'),
    url(r'^BSEE_1st_Year_I/$', views.students_bsee1I, name='students_bsee1I'),
    url(r'^BSEE_2nd_Year/$', views.students_bsee2, name='students_bsee2'),
    url(r'^BSEE_2nd_Year_I/$', views.students_bsee2I, name='students_bsee2I'),
    url(r'^BSEE_3rd_Year/$', views.students_bsee3, name='students_bsee3'),
    url(r'^BSEE_3rd_Year_I/$', views.students_bsee3I, name='students_bsee3I'),
    url(r'^BSEE_4th_Year/$', views.students_bsee4, name='students_bsee4'),
    url(r'^BSEE_4th_Year_I/$', views.students_bsee4I, name='students_bsee4I'),
    url(r'^BSEE_5th_Year/$', views.students_bsee5, name='students_bsee5'),
    url(r'^BSEE_5th_Year_I/$', views.students_bsee5I, name='students_bsee5I'),
    url(r'^BSEE_6th_Year/$', views.students_bsee6, name='students_bsee6'),
    url(r'^BSEE_6th_Year_I/$', views.students_bsee6I, name='students_bsee6I'),

    url(r'^BSEE_1st_Year/$', views.students_bsee1, name='students_bsee1'),
    url(r'^BSEE_2nd_Year/$', views.students_bsee2, name='students_bsee2'),
    url(r'^BSEE_3rd_Year/$', views.students_bsee3, name='students_bsee3'),
    url(r'^BSEE_4th_Year/$', views.students_bsee4, name='students_bsee4'),
    url(r'^BSEE_5th_Year/$', views.students_bsee5, name='students_bsee5'),
    url(r'^BSEE_6th_Year/$', views.students_bsee6, name='students_bsee6'),
    url(r'^BSEE_1st_Year_Block_2/$', views.students_bsee1_2, name='students_bsee1-2'),
    url(r'^BSEE_1st_Year_Block_3/$', views.students_bsee1_3, name='students_bsee1-3'),
    url(r'^BSEE_1st_Year_Block_4/$', views.students_bsee1_4, name='students_bsee1-4'),
    url(r'^BSEE_1st_Year_Block_5/$', views.students_bsee1_5, name='students_bsee1-5'),
    url(r'^BSEE_1st_Year_Block_6/$', views.students_bsee1_6, name='students_bsee1-6'),
    url(r'^BSEE_2nd_Year_Block_1/$', views.students_bsee2_1, name='students_bsee2-1'),
    url(r'^BSEE_2nd_Year_Block_2/$', views.students_bsee2_2, name='students_bsee2-2'),
    url(r'^BSEE_2nd_Year_Block_3/$', views.students_bsee2_3, name='students_bsee2-3'),
    url(r'^BSEE_2nd_Year_Block_4/$', views.students_bsee2_4, name='students_bsee2-4'),
    url(r'^BSEE_2nd_Year_Block_5/$', views.students_bsee2_5, name='students_bsee2-5'),
    url(r'^BSEE_2nd_Year_Block_6/$', views.students_bsee2_6, name='students_bsee2-6'),
    url(r'^BSEE_3rd_Year_Block_1/$', views.students_bsee3_1, name='students_bsee3-1'),
    url(r'^BSEE_3rd_Year_Block_2/$', views.students_bsee3_2, name='students_bsee3-2'),
    url(r'^BSEE_3rd_Year_Block_3/$', views.students_bsee3_3, name='students_bsee3-3'),
    url(r'^BSEE_3rd_Year_Block_4/$', views.students_bsee3_4, name='students_bsee3-4'),
    url(r'^BSEE_3rd_Year_Block_5/$', views.students_bsee3_5, name='students_bsee3-5'),
    url(r'^BSEE_3rd_Year_Block_6/$', views.students_bsee3_6, name='students_bsee3-6'),
    url(r'^BSEE_4th_Year_Block_1/$', views.students_bsee4_1, name='students_bsee4-1'),
    url(r'^BSEE_4th_Year_Block_2/$', views.students_bsee4_2, name='students_bsee4-2'),
    url(r'^BSEE_4th_Year_Block_3/$', views.students_bsee4_3, name='students_bsee4-3'),
    url(r'^BSEE_4th_Year_Block_4/$', views.students_bsee4_4, name='students_bsee4-4'),
    url(r'^BSEE_4th_Year_Block_5/$', views.students_bsee4_5, name='students_bsee4-5'),
    url(r'^BSEE_4th_Year_Block_6/$', views.students_bsee4_6, name='students_bsee4-6'),
    url(r'^BSEE_5th_Year_Block_1/$', views.students_bsee5_1, name='students_bsee5-1'),
    url(r'^BSEE_5th_Year_Block_2/$', views.students_bsee5_2, name='students_bsee5-2'),
    url(r'^BSEE_5th_Year_Block_3/$', views.students_bsee5_3, name='students_bsee5-3'),
    url(r'^BSEE_5th_Year_Block_4/$', views.students_bsee5_4, name='students_bsee5-4'),
    url(r'^BSEE_5th_Year_Block_5/$', views.students_bsee5_5, name='students_bsee5-5'),
    url(r'^BSEE_5th_Year_Block_6/$', views.students_bsee5_6, name='students_bsee5-6'),
    url(r'^BSEE_6th_Year_Block_1/$', views.students_bsee6_1, name='students_bsee6-1'),
    url(r'^BSEE_6th_Year_Block_2/$', views.students_bsee6_2, name='students_bsee6-2'),
    url(r'^BSEE_6th_Year_Block_3/$', views.students_bsee6_3, name='students_bsee6-3'),
    url(r'^BSEE_6th_Year_Block_4/$', views.students_bsee6_4, name='students_bsee6-4'),
    url(r'^BSEE_6th_Year_Block_5/$', views.students_bsee6_5, name='students_bsee6-5'),
    url(r'^BSEE_6th_Year_Block_6/$', views.students_bsee6_6, name='students_bsee6-6'),

    url(r'^edit_students/(?P<pk>\d+)$', views.edit_students, name='edit_students'),
    url(r'^Manage_bsit1B1/$', views.students_bsit1B1, name='students_bsit1B1'),
    url(r'^Manage_bsit1B2/$', views.students_bsit1B2, name='students_bsit1B2'),
    url(r'^Manage_bsit1B3/$', views.students_bsit1B3, name='students_bsit1B3'),
    url(r'^Manage_bsit1B4/$', views.students_bsit1B4, name='students_bsit1B4'),
    url(r'^Manage_bsit1B5/$', views.students_bsit1B5, name='students_bsit1B5'),
    url(r'^Manage_bsit1B6/$', views.students_bsit1B6, name='students_bsit1B6'),

    url(r'^Manage_bsit2B1/$', views.students_bsit2B1, name='students_bsit2B1'),
    url(r'^Manage_bsit2B2/$', views.students_bsit2B2, name='students_bsit2B2'),
    url(r'^Manage_bsit2B3/$', views.students_bsit2B3, name='students_bsit2B3'),
    url(r'^Manage_bsit2B4/$', views.students_bsit2B4, name='students_bsit2B4'),
    url(r'^Manage_bsit2B5/$', views.students_bsit2B5, name='students_bsit2B5'),
    url(r'^Manage_bsit2B6/$', views.students_bsit2B6, name='students_bsit2B6'),

    url(r'^Manage_bsit3B1/$', views.students_bsit3B1, name='students_bsit3B1'),
    url(r'^Manage_bsit3B2/$', views.students_bsit3B2, name='students_bsit3B2'),
    url(r'^Manage_bsit3B3/$', views.students_bsit3B3, name='students_bsit3B3'),
    url(r'^Manage_bsit3B4/$', views.students_bsit3B4, name='students_bsit3B4'),
    url(r'^Manage_bsit3B5/$', views.students_bsit3B5, name='students_bsit3B5'),
    url(r'^Manage_bsit3B6/$', views.students_bsit3B6, name='students_bsit3B6'),

    url(r'^Manage_bsit4B1/$', views.students_bsit4B1, name='students_bsit4B1'),
    url(r'^Manage_bsit4B2/$', views.students_bsit4B2, name='students_bsit4B2'),
    url(r'^Manage_bsit4B3/$', views.students_bsit4B3, name='students_bsit4B3'),
    url(r'^Manage_bsit4B4/$', views.students_bsit4B4, name='students_bsit4B4'),
    url(r'^Manage_bsit4B5/$', views.students_bsit4B5, name='students_bsit4B5'),
    url(r'^Manage_bsit4B6/$', views.students_bsit4B6, name='students_bsit4B6'),

    url(r'^Manage_bsit5B1/$', views.students_bsit5B1, name='students_bsit5B1'),
    url(r'^Manage_bsit5B2/$', views.students_bsit5B2, name='students_bsit5B2'),
    url(r'^Manage_bsit5B3/$', views.students_bsit5B3, name='students_bsit5B3'),
    url(r'^Manage_bsit5B4/$', views.students_bsit5B4, name='students_bsit5B4'),
    url(r'^Manage_bsit5B5/$', views.students_bsit5B5, name='students_bsit5B5'),
    url(r'^Manage_bsit5B6/$', views.students_bsit5B6, name='students_bsit5B6'),

    url(r'^Manage_bsit6B1/$', views.students_bsit6B1, name='students_bsit6B1'),
    url(r'^Manage_bsit6B2/$', views.students_bsit6B2, name='students_bsit6B2'),
    url(r'^Manage_bsit6B3/$', views.students_bsit6B3, name='students_bsit6B3'),
    url(r'^Manage_bsit6B4/$', views.students_bsit6B4, name='students_bsit6B4'),
    url(r'^Manage_bsit6B5/$', views.students_bsit6B5, name='students_bsit6B5'),
    url(r'^Manage_bsit6B6/$', views.students_bsit6B6, name='students_bsit6B6'),

    url(r'^edit_studentsbsee/(?P<pk>\d+)$', views.edit_studentsbsee, name='edit_studentsbsee'),
    url(r'^Manage_bsee1B1/$', views.students_bsee1B1, name='students_bsee1B1'),
    url(r'^Manage_bsee1B2/$', views.students_bsee1B2, name='students_bsee1B2'),
    url(r'^Manage_bsee1B3/$', views.students_bsee1B3, name='students_bsee1B3'),
    url(r'^Manage_bsee1B4/$', views.students_bsee1B4, name='students_bsee1B4'),
    url(r'^Manage_bsee1B5/$', views.students_bsee1B5, name='students_bsee1B5'),
    url(r'^Manage_bsee1B6/$', views.students_bsee1B6, name='students_bsee1B6'),

    url(r'^Manage_bsee2B1/$', views.students_bsee2B1, name='students_bsee2B1'),
    url(r'^Manage_bsee2B2/$', views.students_bsee2B2, name='students_bsee2B2'),
    url(r'^Manage_bsee2B3/$', views.students_bsee2B3, name='students_bsee2B3'),
    url(r'^Manage_bsee2B4/$', views.students_bsee2B4, name='students_bsee2B4'),
    url(r'^Manage_bsee2B5/$', views.students_bsee2B5, name='students_bsee2B5'),
    url(r'^Manage_bsee2B6/$', views.students_bsee2B6, name='students_bsee2B6'),

    url(r'^Manage_bsee3B1/$', views.students_bsee3B1, name='students_bsee3B1'),
    url(r'^Manage_bsee3B2/$', views.students_bsee3B2, name='students_bsee3B2'),
    url(r'^Manage_bsee3B3/$', views.students_bsee3B3, name='students_bsee3B3'),
    url(r'^Manage_bsee3B4/$', views.students_bsee3B4, name='students_bsee3B4'),
    url(r'^Manage_bsee3B5/$', views.students_bsee3B5, name='students_bsee3B5'),
    url(r'^Manage_bsee3B6/$', views.students_bsee3B6, name='students_bsee3B6'),

    url(r'^Manage_bsee4B1/$', views.students_bsee4B1, name='students_bsee4B1'),
    url(r'^Manage_bsee4B2/$', views.students_bsee4B2, name='students_bsee4B2'),
    url(r'^Manage_bsee4B3/$', views.students_bsee4B3, name='students_bsee4B3'),
    url(r'^Manage_bsee4B4/$', views.students_bsee4B4, name='students_bsee4B4'),
    url(r'^Manage_bsee4B5/$', views.students_bsee4B5, name='students_bsee4B5'),
    url(r'^Manage_bsee4B6/$', views.students_bsee4B6, name='students_bsee4B6'),

    url(r'^sManage_bsee5B1/$', views.students_bsee5B1, name='students_bsee5B1'),
    url(r'^Manage_bsee5B2/$', views.students_bsee5B2, name='students_bsee5B2'),
    url(r'^Manage_bsee5B3/$', views.students_bsee5B3, name='students_bsee5B3'),
    url(r'^Manage_bsee5B4/$', views.students_bsee5B4, name='students_bsee5B4'),
    url(r'^Manage_bsee5B5/$', views.students_bsee5B5, name='students_bsee5B5'),
    url(r'^Manage_bsee5B6/$', views.students_bsee5B6, name='students_bsee5B6'),

    url(r'^Manage_bsee6B1/$', views.students_bsee6B1, name='students_bsee6B1'),
    url(r'^Manage_bsee6B2/$', views.students_bsee6B2, name='students_bsee6B2'),
    url(r'^Manage_bsee6B3/$', views.students_bsee6B3, name='students_bsee6B3'),
    url(r'^Manage_bsee6B4/$', views.students_bsee6B4, name='students_bsee6B4'),
    url(r'^Manage_bsee6B5/$', views.students_bsee6B5, name='students_bsee6B5'),
    url(r'^Manage_bsee6B6/$', views.students_bsee6B6, name='students_bsee6B6'),

    url(r'^Faculty/$', views.full_time, name='full_time'),
    path('faculty_schedule/<dept_id>', views.faculty_schedule, name='faculty_schedule'),
    url(r'^chairperson_faculty/(?P<id>[a-zA-Z0-9]+)/edit/$', views.chairperson_faculty_schedule_edit, name="faculty_edit"),
    url(r'^chairperson_faculty/(?P<id>[a-zA-Z0-9]+)/edit/remove=(?P<sid>[a-zA-Z0-9]+)$', views.remove_faculty_schedule),
    url(r'^chairperson_faculty/(?P<id>[a-zA-Z0-9]+)/edit/add=(?P<sid>[a-zA-Z0-9]+$)', views.add_faculty_schedule),

    url(r'^part_time/$', views.part_time, name='part_time'),
    

    # Faculty
    url(r'^fHome/$', views.fHome, name='fHome'),
    url(r'^fProfile/$', views.fProfile, name='fProfile'),
    url(r'^fHomeNotification/$', views.fHomeNotification, name='fHomeNotification'),
    url(r'^fProfileEdit/$', views.fProfileEdit, name='fProfileEdit'),
    url(r'^fProfileChangePass/$', views.fProfileChangePass, name='fProfileChangePass'),
    url(r'^parttime_sched/$', views.parttime_sched, name='parttime_sched'),
    url(r'^fStudents_advisory/$', views.fStudents_advisory, name='fStudents_advisory'),
    path(r'^viewstudent/<sched_id>$', views.fviewstudent, name='viewstudent'),
    url(r'^fStudents_viewStudentGrade/$', views.fStudents_viewStudentGrade, name='fStudents_viewStudentGrade'),
    url(r'^fViewSched/$', views.fViewSched, name='fViewSched'),
    path(r'^fStudents_viewStudentGrade/<stud_id>$', views.fStudents_viewStudentGrade, name='fStudents_viewStudentGrade'),
     
    #STUDENT  PART
    url(r'^student/$', views.student, name='student'),
    url(r'^student_change_password/$', views.student_change_password, name='student_change_password'),
    url(r'^student_clearance/$', views.student_clearanceform, name='scform'),
    #student home and profile
    url(r'^sHome/$', views.sHome, name='sHome'),
    url(r'^sHomeNotifications/$', views.sHomeNotifications, name='sHomeNotifications'),
    url(r'^sProfile/$', views.sProfile, name='sProfile'),
    url(r'^sProfileChangePass/$', views.sProfileChangePass, name='sProfileChangePass'),
    url(r'^sProfileEdit/$', views.sProfileEdit, name='sProfileEdit'),
    #checklist
    url(r'^sChecklist/$', views.sChecklist, name='sChecklist'),
    path(r'^sChecklistEmptyConfirmation/<currchecklist_id>$', views.sChecklistEmptyConfirmation, name='sChecklistEmptyConfirmation'),
    #classroon
    url(r'^sClassroom/$', views.sClassroom, name='sClassroom'),
    #grade submission
    url(r'^sGradeSubmission1/$', views.sGradeSubmission1, name='sGradeSubmission1'),
    url(r'^sGradeSubmission2/$', views.sGradeSubmission2, name='sGradeSubmission2'),
    url(r'^sGradeSubmission3/$', views.sGradeSubmission3, name='sGradeSubmission3'),
    url(r'^donecrs/$', views.donecrs, name='donecrs'),
    #student view sched
    url(r'^sScheduleView/$', views.sScheduleView, name='sScheduleView'),
    #student notification
    url(r'^HDNotifdetails/$', views.HDNotif, name='HDNotifdetails'),
    url(r'^LOANotifdetails/$', views.LOANotif, name='LOANotifdetails'),
    url(r'^SPNotifdetails/$', views.SPNotif, name='SPNotifdetails'),
    url(r'^OJTNotifdetails/$', views.OJTNotif, name='OJTNotifdetails'),
    url(r'^GradesNotifdetails/$', views.GradesNotif, name='GradesNotifdetails'),

    #student others
    url(r'^sOthers/$', views.sOthers, name='sOthers'),
    #student Hd
    url(r'^HD_DownloadDF/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^sHd1/$', views.sHd1, name='sHd1'),
    url(r'^scf/$', views.Student_Clearance, name='scf'),
    url(r'^sHd2/$', views.sHd2, name='sHd2'),
    url(r'^sHd3/$', views.sHd3, name='sHd3'),
    url(r'^stc/$', views.Student_Transfer, name='stc'),
    url(r'^sHd4/$', views.sHd4, name='sHd4'),
    url(r'^sHd5/$', views.sHd5, name='sHd5'),
    url(r'^doneHd/$', views.doneHd, name='doneHd'),
    #student Loa
    url(r'^sLoa1/$', views.sLoa1, name='sLoa1'),
    url(r'^lscf/$', views.Loa_Clearance, name='lscf'),
    url(r'^sLoa2/$', views.sLoa2, name='sLoa2'),
    url(r'^lf/$', views.Loa_Form, name='lf'),
    url(r'^sLoa3/$', views.sLoa3, name='sLoa3'),
    url(r'^sLoa4/$', views.sLoa4, name='sLoa4'),
    url(r'^doneLoa/$', views.doneLoa, name='doneLoa'),
    #student_ojt
    path(r'^sPracticum2/$', views.sPracticum2, name='sPracticum2'),
    url(r'^sPracticum1/$', views.sPracticum1, name='sPracticum1'),
    url(r'^donepracticum/$', views.donepracticum, name='donepracticum'),
    #student studyplan
    url(r'^stdplnyr/$', views.studyplan1, name='stdplnyr'),
    url(r'^stdplnsub/$', views.studyplan2, name='stdplnsub'),
    url(r'^stdplnview/$', views.studyplan3, name='stdplnview'),
    url(r'^DLstdpln/$', views.download_stdpln, name='DLstdpln'),
    url(r'^stdplnul/$', views.studyplan4, name='stdplnul'),
    url(r'^stdplncs/$', views.studyplan5, name='stdplncs'),
    url(r'^sptest/$', views.sptest, name='sptest'),
    url(r'^donesp/$', views.donesp, name='donesp'),
    #END OF STUDENT PART

    #Faculty Applicant 
    url(r'^applicant/$', views.applicant, name='applicant'),
    url(r'^admin/$', views.applicant, name='admin'),
    url(r'^faculty_applicant/$', views.faculty_applicant, name='faculty_applicant'),
    url(r'^applicant_facultyapplicationform/$', views.applicant_facultyapplicationform, name='applicant_facultyapplicationform'),
    url(r'^applicant_successfullysubmitted/$', views.applicant_successfullysubmitted, name='applicant_successfullysubmitted'),
    url(r'^applicantrequirements/$', views.applicantrequirements, name='applicantrequirements'),
    url(r'^faculty_applicant_form/$', views.faculty_applicant_form, name='faculty_applicant_form'),
    url(r'^faculty_applicant_form_submitted/$', views.faculty_applicant_form_submitted, name='faculty_applicant_form_submitted'),
    url(r'^cOthers-partTime/$',views.pta_request, name='cOthers-partTime'),
    path(r'^cOthers-partTimeView/<pt_id>$',views.pta_view,name='cOthers-partTimeView'),
    #Student Applicant 
    url(r'^student_applicant/$', views.student_applicant, name='student_applicant'),
    path(r'cOthers-transferee', views.transferee_list, name='cOthers-transferee'),
    path(r'cOthers-transfereeView/<transf_id>', views.transferee_view, name='cOthers-transfereeView'),
    path(r'cOthers-transferee-feedback/<transf_id>', views.transferee_feedback, name='cOthers-transferee-feedback'),
    path(r'cOthers-transferee-csw/<transf_id>', views.transferee_csw, name="cOthers-transferee-csw"),
    path(r'transferee_Pdf/<transf_id>', views.transferee_Pdf, name="transferee_Pdf"),
    path(r'del_alltransferee/<transf_id>', views.del_alltransferee, name="del_alltransferee"),
    url(r'^transferee_1requirements/$', views.transferee_1requirements, name='transferee_1requirements'),
    url(r'^transferee_2GWA/$', views.transferee_2GWA, name='transferee_2GWA'),
    url(r'^transferee_3.2GWANotQual/$', views.transferee_3_2GWANotQual, name='transferee_3.2GWANotQual'),
    url(r'^transferee_3GWAQual/$', views.transferee_3GWAQual, name='transferee_3GWAQual'),
    url(r'^transferee_9applicationform/$', views.transferee_9applicationform, name='transferee_9applicationform'),
    url(r'^transferee_10success/$', views.transferee_10success, name='transferee_10success'),
    url(r'^shifter1/$', views.shifter1, name='shifter1'),
    url(r'^shifter2/$', views.shifter2, name='shifter2'),
    url(r'^shifter3.2/$', views.shifter3_2, name='shifter3.2'),
    url(r'^shifter3/$', views.shifter3, name='shifter3'),
    url(r'^shifter9/$', views.shifter9, name='shifter9'),
    url(r'^shifter10/$', views.shifter10, name='shifter10'),


    #CHAIRPERSON OTHERS
    #HD 
    url(r'^cOthers-hd/$', views.hd_general, name='cOthers-hd'),
    path(r'^cOthers-hdView/<hd_id>$', views.hd_view, name='cOthers-hdView'),
    path(r'^feedback/<hd_id>$', views.feedback, name='feedback'),
    path(r'^message/<hd_id>$', views.message, name='message'),
    path(r'^sendingemailHD/<hd_id>$', views.sendingemailHD, name='sendingemailHD'),
    path(r'^del_allHD/<hd_id>$', views.del_allHD, name='del_allHD'),
    path(r'cOthers-hd-Master/', views.hd_masterlist, name='cOthers-hd-Master'),
    #StudyPlan
    url(r'^cOthers-studyPlan/$', views.sp_general, name='cOthers-studyPlan'),
    path(r'^cOthers-studyPlanView/<sp_id>$', views.sp_view, name='cOthers-studyPlanView'),
    path(r'^del_allSP/<sp_id>$', views.del_allSP, name='del_allSP'),
    path(r'^feedbacksp/<sp_id>$', views.feedbacksp, name='feedbacksp'),
    path(r'^messagesp/<sp_id>$', views.messagesp, name='messagesp'),
    path(r'cOthers-studyPlan-Master/', views.sp_masterlist, name='cOthers-studyPlan-Master'),
    #LOA
    path(r'cOthers-loa/', views.loa_list, name='cOthers-loa'),
    path(r'cOthers-loa-Master/', views.loa_masterlist, name='cOthers-loa-Master'),
    path(r'cOthers-loaView/<loa_id>', views.loa_view, name='cOthers-loaView'),
    path(r'cOthers-loa-feedback/<loa_id>', views.Loa_feedback, name='cOthers-loa-feedback'),
    path(r'cOthers-loa-csw/<loa_id>', views.loa_csw, name="cOthers-loa-csw"),
    path(r'attach/<attach_id>', views.attach, name="attach"),
    path(r'loa_Pdf/<loa_id>', views.loa_Pdf, name="loa_Pdf"),
    path(r'sendmailwfile/<email_id>', views.sendmailwfile, name="sendmailwfile"),
    path(r'del_allLOA/<loa_id>', views.del_allLOA, name="del_allLOA"),
    #OJT
    path(r'cOthers-ojt/', views.ojt_general, name='cOthers-ojt'),
    path(r'cOthers-ojtView/<ojt_id>', views.ojt_view, name='cOthers-ojtView'),
    path(r'^ojt_feedback/<ojt_id>$', views.ojt_feedback, name='ojt_feedback'),
    path(r'^ojt_message/<ojt_id>$', views.ojt_message, name='ojt_message'),
    path(r'^del_allojt/<ojt_id>$', views.del_allojt, name='del_allojt'),
    path(r'^sendingemailOJT/<ojt_id>$', views.sendingemailOJT, name='sendingemailOJT'),
    path(r'cOthers-ojt-Master/', views.ojt_masterlist, name='cOthers-ojt-Master'),
    #SHIFTERS
    path(r'cOthers-shifter', views.shifter_list, name='cOthers-shifter'),
    path(r'cOthers-shifter-Master/', views.shifter_masterlist, name='cOthers-shifter-Master'),
    path(r'cOthers-shifterView/<shift_id>', views.shifter_view, name='cOthers-shifterView'),
    path(r'cOthers-shifter-feedback/<shift_id>', views.shifter_feedback, name='cOthers-shifter-feedback'),
    path(r'cOthers-shifter-csw/<shift_id>', views.shifter_csw, name="cOthers-shifter-csw"),
    path(r'shifter_Pdf/<shift_id>', views.shifter_Pdf, name="shifter_Pdf"),
    path(r'del_allshifter/<shift_id>', views.del_allshifter, name="del_allshifter"),
    #TRANSFEREE
    path(r'cOthers-transferee', views.transferee_list, name='cOthers-transferee'),
    path(r'cOthers-transferee-Master/', views.transferee_masterlist, name='cOthers-transferee-Master'),
    path(r'cOthers-transfereeView/<transf_id>', views.transferee_view, name='cOthers-transfereeView'),
    path(r'cOthers-transferee-feedback/<transf_id>', views.transferee_feedback, name='cOthers-transferee-feedback'),
    path(r'cOthers-transferee-csw/<transf_id>', views.transferee_csw, name="cOthers-transferee-csw"),
    path(r'transferee_Pdf/<transf_id>', views.transferee_Pdf, name="transferee_Pdf"),
    path(r'del_alltransferee/<transf_id>', views.del_alltransferee, name="del_alltransferee"),
    path(r'notifications/<notification_id>', views.notifications, name='notifications'),

    #etc 
    url(r'^admin/$', views.admin, name='admin'),
    
    #scheduling urls
    url(r'^cStudentViewBlock/$', views.viewblock, name='cStudentViewBlock'),
    url(r'^cStudentSchedOnline/$', views.schedOnline, name='cStudentSchedOnline'),
    path(r'^cStudentSchedOnline2/<block_id>$', views.schedOnline2, name='cStudentSchedOnline2'),
    url(r'^cStudentDeleteSched/(?P<block_id>[a-zA-Z0-9]+)/(?P<sec_id>[a-zA-Z0-9]+$)', views.cStudentDeleteSched, name='cStudentDeleteSched'),

    # pw_reset
    path('password_reset/', views.pw_reset, name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='pw_reset/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='pw_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='pw_reset/password_reset_complete.html'),
         name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
